CREATE DATABASE taskdb;
CREATE USER taskuser WITH ENCRYPTED PASSWORD 'taskpass';
GRANT ALL PRIVILEGES ON DATABASE taskdb TO taskuser;
\c taskdb
CREATE SCHEMA IF NOT EXISTS task_schema AUTHORIZATION taskuser;
GRANT ALL PRIVILEGES ON SCHEMA task_schema TO taskuser;
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
